### ISSUE TITLE
Typescript strict mode supported?

### ISSUE THREAD

**Issue by jvanbruegge** [Swizz/snabbdom-pragma#12]
I haven't tried it, but I don't think this works with typescript's `--strict` flag, because of missing JSX namespace declarations

**Comment by Swizz** [comment]
I dont really know typescript. I found the '--jsxFactory' to add the `createElement` pragma.

Snabbdom-pragma, is transpiler independant, and transform `createElement` call to Snabbdom vnode.

**Comment by Swizz** [comment]
Ow. I guess I misunderstood you.

Are you talking about the lack of Typescript type definitions in
Snabbdom-pragma ?

Le 12 mai 2017 17:44, "Jan van Brügge" <notifications@github.com> a écrit :

I haven't tried it, but I don't think this works with typescript's --strict
flag, because of missing JSX namespace declarations

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Swizz/snabbdom-pragma/issues/12>, or mute the thread

**Comment by jvanbruegge** [comment]
Yes, typescript expects a global `JSX` namespace declaration.

**Comment by jvanbruegge** [comment]
More info here: https://github.com/cyclejs-community/create-cycle-app-flavors/issues/21

**Comment by Swizz** [comment]
So, to solve this issue I need to write a Typescript declaration file ?

Both for JSX and Snabbdom Vnode ?

https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by jvanbruegge** [comment]
Snabbdom provides a declaration for VNode, but it seems we need something like this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/df09b2a3368b7f47959f86247a12ab95b9d261f4/types/react/index.d.ts#L2721

**Comment by Swizz** [comment]
Thank you. I will take a look.

This is a great trigger to start to learn Typescript !

Can I refer to the Snabbdom Vnode declaration from Snabbdom-pragma one ?

**Comment by jvanbruegge** [comment]
`import { VNode } from 'snabbdom';`

**Comment by Swizz** [comment]
Live on : [feature/definitely-typed](https://github.com/Swizz/snabbdom-pragma/tree/feature/definitely-typed)

This is a pretty naive [implementation](https://github.com/Swizz/snabbdom-pragma/blob/feature/definitely-typed/snabbdom-pragma.d.ts) but seem to fill all the needs.
Give it a try, and feel free to contribute.

**Comment by Swizz** [comment]
@jvanbruegge Did you take an eye on it ? This is what you need ?

**Comment by jvanbruegge** [comment]
I think it is, but can you publish it as alpha release, then I can test properly

**Comment by Swizz** [comment]
Couldn't you npm install it from branch ?
```
Swizz/Snabbdom-pragam#feature/definitely-typed
```

**Comment by jvanbruegge** [comment]
Yeah, that worked.
You don't get errors with this, sadly you have to put a `/// <reference>` in your code to make it work

**Comment by Swizz** [comment]
I will dive into Typescript someday soon, I promise.

As this change is not really a breaking one, I can release it at your go.

**Comment by jvanbruegge** [comment]
yeah, go for it
we can improve the typings in the future

**Comment by Swizz** [comment]
Npm published : [v2.2.0](https://github.com/Swizz/snabbdom-pragma/releases/tag/2.2.0)
