### ISSUE TITLE
Add ES6 module build

### ISSUE THREAD

**Issue by jvanbruegge** [Swizz/snabbdom-pragma#20]
For scope hoisting. Might allow prepack to remove this module entirely

**Comment by jvanbruegge** [comment]
`jsnext:main` is deprecated. `module` is the one. Does buble leave the Es6 exports and imports in there?

**Comment by Swizz** [comment]
Yes. Using `-no modules` Buble dont care about `export`/`import`.
So what do you need/want ?

**Comment by jvanbruegge** [comment]
a `dist/index.es6.js` compiled with `-no modules` and a `module: "dist/index.es6.js" ` in the package.json

**Comment by Swizz** [comment]
oups

**Comment by Swizz** [comment]
So you will have the 3 src files compiled but not bundled. This is what you want ?

**Comment by jvanbruegge** [comment]
I did it myself, thanks to your use of rollup this was rather easy to do

**Comment by Swizz** [comment]
I will merge it ASAP
