### ISSUE TITLE
Setting a data attribute with more than one dash does not work

### ISSUE THREAD

**Issue by blikblum** [Swizz/snabbdom-pragma#26]
Actual example:

```
let calcKey = 'x'
return <a data-calc-key={calcKey}>
```

Will set el.dataset.calc to [Object object] instead of setting  el.dataset.calcKey to 'x'

The reason is that the following params will be passed:

```
{
  data: {
    calc: {
       key: 'x'
    }
  }
}
```

This struct is created by `deepifyKeys`

**Comment by blikblum** [comment]
I tried  `<a data={{'calc-key': calcKey}}>` but an error occurs inside dataset module so seems is not doable to implement this use case. Anyway it would be good to document the behavior

This works: `<a data={{calcKey: calcKey}}>`

**Comment by blikblum** [comment]
While for data- attributes will not work with property with dash, style accepts property with dashs so something like:

`return <a style-background-color={'blue'}>` will not work due to the way `deepifyKeys` works

**Comment by Swizz** [comment]
`deepifyKeys` is parth of the [Modules as attributes feature](https://github.com/Swizz/snabbdom-pragma#modules-attribute)
Allowing you to consume Snabbdom modules from attributes without worrying about using object.

The drawback of this feature is every attribute using dash is considered as a module key, giving you the opportunity to set deep objects.

**Comment by blikblum** [comment]
> deepifyKeys is parth of the Modules as attributes feature

I've got that.

My issue is when the property has a dash, something like `MODULE-PROPERTY-WITHDASH`

I would expect that `<div style-background-color={'blue'}>` would set `style.background-color` property to 'blue'. The equivalent to `h('div', {style: {'background-color': 'blue'}})` but instead it sets `h('div', {style: {background: {color: 'blue'}}})`.

IMO is a bug but if not at least should be documented

**Comment by Swizz** [comment]
Snabbdom style module is using the both way to define style.

```js
if (name[0] === '-' && name[1] === '-') {
  (elm as any).style.setProperty(name, cur);
} else {
  (elm as any).style[name] = cur;
}
```

As style in JS is mean to be used that way, you should really go using camelCase styles.

```jsx
<div style-backgroundColor ={'blue'}></div>
```

But we should consider to do not split more than the first dash.

**Comment by blikblum** [comment]
> As style in JS is mean to be used that way, you should really go using camelCase styles

This is an option for style, but in case of class there is no option when the class name has a dash in it. With the current implementation, the example bellow will set 'alert' class instead of 'alert-primary':

`<div class-alert-primary={true}></div>`

In fact snabbdom modules handle properties with dash slightly different:

_style module_:

Accepts  both properties with dash or with camel-case

```
h('div', {style: {'background-color': 'blue'}})

h('div', {style: {'backgroundColor': 'blue'}})
```
The examples below will produce the same effect

_class module_

Requires to use the property with dash because the camelCase one will match a different class

```
h('div', {style: {alertPrimary: true}}) // sets alertPrimary class

h('div', {style: {'alert-primary': true}}) // sets alert-primary class
```

_dataset/data module_:

An error occurs when using properties with dash (a restriction of `HTMLElement.dataset`)

```
h('div', {style: {itemKey: 1}}) //fine

h('div', {style: {'item-key': 1}}) // throws
```

In my option only the first dash should be split. Also, should be documented that dataset/data module does not accepts properties with dash
