### ISSUE TITLE
 Add more docs about the use of modules and Components

### ISSUE THREAD

**Issue by Swizz** [Swizz/snabbdom-pragma#3]
I'll need to add more things to the docs regarding the use of modules and how to use components which is more like snabbdom than 'NotReact'

**Comment by caesarsol** [comment]
Hello,
could you also add some example of uncompiled/compiled/snabbdom-equivalent code snippets on the README?

I think it would be more easy to grasp for beginners.

Thanks!

**Comment by Swizz** [comment]
Hi !
I enjoy your interest on `snabbdom-pragma`. I will try to work on it during this following Easter Day.

I am not really good at making documentations. Could you provide me some examples of your needs ?
Are you asking about something more like [`test/jsx-specs`](https://github.com/Swizz/snabbdom-pragma/tree/master/test/jsx-specs) and [`test/snabbdom-specs`](https://github.com/Swizz/snabbdom-pragma/tree/master/test/snabbdom-specs) as examples ?

Cheers,

**Comment by caesarsol** [comment]
Yes, something like code snippets before and after compilation, just to pass the idea.

Also, I'm curious on how do you pass custom snabbdom data attributes in the JSX props.

Thanks!

**Comment by Swizz** [comment]
As `snabbdom-pragma` Is regardly based on `NotReact.createElement` and `snabbdom` we need to find a better way to explain comparhison regarding `NotReact` and `Snabbdom`. **WIP**

**Comment by caesarsol** [comment]
I'd like to help! 

What is `NotReact` though?

**Comment by Swizz** [comment]
`snabbdom-pragma` aim to handle the same api as `React.createElement`. 
I based my specs test on the [`React.createElement` documentation](https://facebook.github.io/react/docs/react-api.html#createelement) and [some React derivated projects](https://github.com/infernojs/inferno/tree/master/packages/inferno-create-element).

So, I chose to try to call all React API compatible projects `NotReact` things.

---

I think I will divide the documentation in four parts : 
- Usage with Transpilers
  * Bublé
  * Babel
  * Traceur
- JSX Features
  * Elements
  * Attributes
  * SVG
- Snabbdom Features
  * Modules object
  * Modules attribute
- 'NotReact' Features
  * Components

**Comment by Swizz** [comment]
[Here](https://gist.github.com/Swizz/e52e8abc020fc39a2217fc96ff5ccb02), what I had in mind

**Comment by caesarsol** [comment]
I think that's very clearly explained!

A couple minor notes:
- In the Module Object section, the style prop is formatted as a string, isn't that supposed to be an object? 
- About the NotReact convention, I think you could clear any confusion by linking every reference to a short document of yours explaining the details.
- If I'm not wrong, the module is completely compiler-independent. You should mention that because it's a giant plus!

Thank for your work, I'll contribute whenever I find the occasion!

**Comment by Swizz** [comment]
Branch opened for contributions : [feature/write-some-docs](https://github.com/Swizz/snabbdom-pragma/tree/feature/write-some-docs)
I will merge it within days.

**Comment by Swizz** [comment]
Now on [develop](https://github.com/Swizz/snabbdom-pragma/tree/develop), will be released on NPM with the v2 I guess

**Comment by Swizz** [comment]
[v2.0.0](https://github.com/Swizz/snabbdom-pragma/releases/tag/2.0.0) now on air

**Comment by Swizz** [comment]
@caesarsol
> If I'm not wrong, the module is completely compiler-independent. You should mention that because it's a giant plus!

It is a YES ! [Typescript support added in few minutes](https://github.com/Swizz/snabbdom-pragma/commit/66c114cb8404c845e16b96bdef98884dbae5bb35)
